version: "3.8"

services:
  mc:
    build:
       context: .
       dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-mcaws}
    environment:
      EULA: "TRUE"
      SNOOPER_ENABLED: "false"
      TYPE: "PAPER"
      MEMORY: "2G"
      DIFFICULTY: "normal"
      MOTD: "A very strange server"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - type: bind
        source: ./plugins
        target: /data/plugins
      - type: bind
        source: ./datapacks
        target: /data/world/datapacks
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data:
