version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      RCON_PASSWORD: "test_rcon_minecraft" 
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data:
    name: docker-minecraft-server_data
    external: true

