version: "3.8"

services:
  mc:
    build: .
    image: result/latest 
    environment:
      REPLACE_ENV_VARIABLES: "TRUE" 
      PLUGINS_SYNC_UPDATE: "FALSE" # Allows us to guarantee the that files from mounts/*/ can overwrite its respective files in the docker volume (even if the source is older than the destination)
      REMOVE_OLD_MODS: "TRUE"
      SERVER_NAME: "Regular-Crafts"
      MOTD: "The Regular-Crafts Server"
      TYPE: "PAPER"
      MAX_PLAYERS: 10
      VERSION: "1.20"
      RCON_PASSWORD: "test_rcon_minecraft" 
      EULA: "true"
      SNOOPER_ENABLED: false
      SEED: "-4234144854417651709"
      DIFFICULTY: "Peaceful"
      VIEW_DISTANCE: 16
      FORCE_GAMEMODE: true
      MODE: "survival"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./mounts/plugins:/plugins
      - ./mounts/mods:/mods
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data:
    name: docker-minecraft-server_data
    external: true

