version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      SNOOPER_ENABLED: "false"
      TYPE: "PAPER"
      DIFFICULTY: "normal"
      VIEW_DISTANCE: "10"
      MEMORY: "1G"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data:
