version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      REPLACE_ENV_VARIABLES: "TRUE"
      SERVER_NAME: "Regular-Crafts"
      MOTD: "The Regular-Crafts Server"
      TYPE: "PAPER"
      MAX_PLAYERS: 10
      VERSION: "1.20"
      RCON_PASSWORD: "test_rcon_minecraft" 
      EULA: "true"
      SNOOPER_ENABLED: false
      SEED: "-4234144854417651709"
      VIEW_DISTANCE: 16
      FORCE_GAMEMODE: true
      MODE: "creative"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data:
    name: docker-minecraft-server_data
    external: true

