version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: # allocate from https://console.curseforge.com/
      CF_FORCE_SYNCHRONIZE: "true"
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/valhelsia-5/files/4429560
      MEMORY: 4G
    volumes:
      - data:/data

volumes:
  data: {}