version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      # CF_API_KEY=... must be set in .env file or as environment variable
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: one-block-modded
      # Modpack client zip must be manually downloaded from
      # https://www.curseforge.com/minecraft/modpacks/one-block-modded
      # due to authors disallowing project distribution
      CF_MODPACK_ZIP: /modpacks/Modded+OneBock.zip
      CF_SET_LEVEL_FROM: OVERRIDES
      DEBUG: "false"
      MEMORY: 4G
    volumes:
      - mc-data:/data
      - ./modpacks:/modpacks:ro

volumes:
  mc-data: {}