version: "3"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: QUILT
    ports:
      - "25565:25565"
    volumes:
      - data:/data

volumes:
  data: {}